#!/usr/bin/env node
// BACKLOG-3364: capture REAL PostgREST responses, through the real
// @supabase/supabase-js client, for the membership queries PR 2 / PR 3 build on.
//
//   SUPABASE_URL=http://<tailnet or loopback>:54321 \
//   SUPABASE_JWT_SECRET=<the venue's JWT secret> \
//   node supabase/tests/backlog-3364/postgrest/probe.mjs pre|post
//
// Needs postgrest/seed.sql loaded first and postgrest/cleanup.sql after.
// Writes fixtures/postgrest-<phase>-migration.json.
//
// The JWT secret is the venue's, supplied by whoever runs the probe; it is never
// written anywhere. Tokens are minted locally for the two fixture users and live
// five minutes.
//
// Every UUID in a response is replaced before writing: the fixture ids by
// readable labels, any id the database generated by <generated-uuid-N>. Keys,
// nesting, value types, status codes and error objects are written exactly as
// the client returned them.

import crypto from "node:crypto";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..", "..", "..");
const require = createRequire(join(REPO, "package.json"));
const { createClient } = require("@supabase/supabase-js");
const SUPABASE_JS_VERSION = require("@supabase/supabase-js/package.json").version;

const phase = process.argv[2];
if (phase !== "pre" && phase !== "post") {
  console.error("usage: probe.mjs pre|post");
  process.exit(2);
}
const url = process.env.SUPABASE_URL ?? "";
const secret = process.env.SUPABASE_JWT_SECRET ?? "";
const host = (() => {
  try {
    return new URL(url).hostname;
  } catch {
    return "";
  }
})();
const TAILNET = /^100\.(6[4-9]|[7-9][0-9]|1[0-1][0-9]|12[0-7])\.\d{1,3}\.\d{1,3}$/;
if (!(host === "127.0.0.1" || host === "localhost" || TAILNET.test(host))) {
  console.error(`REFUSING: SUPABASE_URL host '${host}' is neither loopback nor a Tailscale address.`);
  process.exit(2);
}
if (secret.length < 32) {
  console.error("REFUSING: SUPABASE_JWT_SECRET is not set.");
  process.exit(2);
}

const FIXTURE = {
  "00000000-0000-4000-8000-00003364e001": "<fixture:user-brokerage-agent>", // pii-allow-uuid: invented fixture id
  "00000000-0000-4000-8000-00003364e002": "<fixture:user-solo>", // pii-allow-uuid: invented fixture id
  "00000000-0000-4000-8000-00003364e0a0": "<fixture:org-brokerage>", // pii-allow-uuid: invented fixture id
  "00000000-0000-4000-8000-00003364e110": "<fixture:plan-individual>", // pii-allow-uuid: invented fixture id
  "00000000-0000-4000-8000-00003364e120": "<fixture:plan-team>", // pii-allow-uuid: invented fixture id
};
const BROKER = "00000000-0000-4000-8000-00003364e001"; // pii-allow-uuid: invented fixture id
const SOLO = "00000000-0000-4000-8000-00003364e002"; // pii-allow-uuid: invented fixture id

const b64 = (v) => Buffer.from(JSON.stringify(v)).toString("base64url");
function jwt(claims) {
  const now = Math.floor(Date.now() / 1000);
  const head = b64({ alg: "HS256", typ: "JWT" });
  const body = b64({ iss: "supabase-demo", iat: now, exp: now + 300, ...claims });
  const sig = crypto.createHmac("sha256", secret).update(`${head}.${body}`).digest("base64url");
  return `${head}.${body}.${sig}`;
}
const anonKey = jwt({ role: "anon" });
function clientFor(userId) {
  const token = jwt({ role: "authenticated", aud: "authenticated", sub: userId });
  return createClient(url, anonKey, {
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
    global: { headers: { Authorization: `Bearer ${token}` } },
  });
}

async function capture(label, description, run) {
  try {
    const r = await run();
    return { label, description, threw: false, status: r.status, statusText: r.statusText, error: r.error, data: r.data };
  } catch (err) {
    return { label, description, threw: true, thrown: String(err) };
  }
}

const broker = clientFor(BROKER);
const solo = clientFor(SOLO);
const members = (c) => c.from("organization_members");

const cases = [];
cases.push(
  await capture("A", 'select("organization_id, organizations(name, personal_owner_user_id)").eq("user_id", <broker>)', () =>
    members(broker).select("organization_id, organizations(name, personal_owner_user_id)").eq("user_id", BROKER),
  ),
);
cases.push(
  await capture("B", 'select("organization_id, organizations(*)").eq("user_id", <broker>)', () =>
    members(broker).select("organization_id, organizations(*)").eq("user_id", BROKER),
  ),
);
cases.push(
  await capture("C", 'B + .order("personal_owner_user_id", { referencedTable: "organizations" })', () =>
    members(broker)
      .select("organization_id, organizations(*)")
      .eq("user_id", BROKER)
      .order("personal_owner_user_id", { referencedTable: "organizations" }),
  ),
);
cases.push(
  await capture("D", 'B + .is("organizations.personal_owner_user_id", null)', () =>
    members(broker).select("organization_id, organizations(*)").eq("user_id", BROKER).is("organizations.personal_owner_user_id", null),
  ),
);
cases.push(
  await capture("E", 'B + .order("created_at") on organization_members', () =>
    members(broker).select("organization_id, organizations(*)").eq("user_id", BROKER).order("created_at"),
  ),
);
const ruling7 = (c, uid) =>
  members(c)
    .select("organization_id, organizations(*)")
    .eq("user_id", uid)
    .eq("license_status", "active")
    .order("created_at", { ascending: true })
    .order("id", { ascending: true });
cases.push(
  await capture("R7-broker", "ruling-7 membership query (3e27deee §7), brokerage agent", () => ruling7(broker, BROKER)),
);
cases.push(await capture("R7-solo-before-ensure", "ruling-7 membership query, solo user before ensure", () => ruling7(solo, SOLO)));
cases.push(await capture("RPC-ensure", 'rpc("ensure_personal_organization") as the solo user', () => solo.rpc("ensure_personal_organization")));
cases.push(await capture("RPC-ensure-again", 'rpc("ensure_personal_organization") second call', () => solo.rpc("ensure_personal_organization")));
cases.push(await capture("R7-solo-after-ensure", "ruling-7 membership query, solo user after ensure", () => ruling7(solo, SOLO)));

// Replace every UUID: fixture ids by label, generated ids by stable placeholders.
const generated = new Map();
const UUID = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi;
const json = JSON.stringify(
  {
    backlog: "BACKLOG-3364",
    phase: `${phase}-migration`,
    captured_at: new Date().toISOString(),
    client: `@supabase/supabase-js ${SUPABASE_JS_VERSION}`,
    venue: "NAS Supabase test stack (Postgres 17.6, PostgREST), see ../README.md",
    note: "UUIDs replaced: fixture ids by <fixture:...> labels, database-generated ids by <generated-uuid-N>. Everything else is verbatim.",
    cases,
  },
  null,
  2,
).replace(UUID, (m) => {
  const k = m.toLowerCase();
  if (FIXTURE[k]) return FIXTURE[k];
  if (!generated.has(k)) generated.set(k, `<generated-uuid-${generated.size + 1}>`);
  return generated.get(k);
});

const out = join(HERE, "..", "fixtures", `postgrest-${phase}-migration.json`);
writeFileSync(out, json + "\n");
for (const c of cases) {
  console.log(
    `${c.label.padEnd(24)} ${c.threw ? "THREW " + c.thrown : `status=${c.status} error=${c.error ? c.error.code : "null"} rows=${Array.isArray(c.data) ? c.data.length : typeof c.data}`}`,
  );
}
console.log(`wrote ${out}`);
