/**
 * withLanCleartext — permit cleartext HTTP so the companion can reach the
 * desktop's local sync server (BACKLOG-2956).
 *
 * ## The defect this fixes
 *
 * Android has blocked cleartext HTTP **by default since API 28**. This app
 * targets 36 and `localSyncService` serves plain `http://` on the LAN, so
 * without an explicit permission the OS refuses the request **before a socket
 * is opened** — pairing and every subsequent sync are dead, and nothing reaches
 * the desktop to be logged.
 *
 * It went unnoticed for the app's whole life because **debug builds get
 * `android:usesCleartextTraffic="true"` injected automatically** (so the Expo
 * dev server is reachable). Every companion build shipped until BACKLOG-2956 —
 * including the one in the field — was a debug APK. The first *release* build
 * removes the injection, and local sync stopped working for everyone.
 *
 * ## Why a config plugin and not app.json
 *
 * `android/` is generated by `expo prebuild --clean` and gitignored, so a
 * hand-edited manifest is wiped by the next build. The setting has to come from
 * config. Two candidates were checked against the PINNED SDK (expo 55.0.30,
 * @expo/config-plugins 55.0.11):
 *
 *   - `expo.android.usesCleartextTraffic` in app.json — **does not exist**.
 *     `@expo/config-types/build/ExpoConfig.d.ts` has no such key at this SDK
 *     (it is `expo-build-properties` that supplies one, and that package is not
 *     a dependency here). Setting it in app.json would be silently ignored,
 *     which is the worst possible outcome for this particular bug.
 *   - `expo-build-properties` — a new dependency for one boolean.
 *
 * So: a local plugin. `@expo/config-plugins` is already in the tree and already
 * types the attribute (`ManifestApplication['android:usesCleartextTraffic']`).
 *
 * ## Why a blanket flag and NOT a narrow networkSecurityConfig
 *
 * The narrow policy — "cleartext for 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
 * and 169.254.0.0/16 only" — is the posture we want and it is **not
 * expressible**. Android's network-security-config `<domain>` element takes
 * hostnames and exact IP literals; it has **no CIDR/subnet syntax**. The
 * desktop's LAN address is not known at build time and the ranges cannot be
 * enumerated (10/8 alone is 16.7M addresses). The only writable NSC forms are a
 * blanket `<base-config cleartextTrafficPermitted="true">` — identical in effect
 * to this attribute, with an extra resource file to keep in sync — or a list of
 * hostnames we do not have.
 *
 * **The private-range restriction is therefore enforced one layer up, in the
 * app:** `services/lanAddress.ts` refuses to talk to any desktop address
 * outside those ranges, before a request is issued. That is what actually
 * bounds the risk this flag opens (a malicious QR code naming a public host
 * would otherwise get SMS content POSTed in cleartext to the internet). Neither
 * half is sufficient alone — if you ever remove one, remove the other
 * deliberately.
 *
 * ## Verification
 *
 * A unit test cannot observe an OS network policy. The authority is the built
 * artifact, asserted by `scripts/build-release.sh` step 8:
 *
 *     aapt2 dump xmltree --file AndroidManifest.xml <apk> | grep -i cleartext
 *
 * Before this plugin that grep returned NOTHING on a release APK. The tests in
 * `__tests__/withLanCleartext.test.js` cover the two ways this can silently
 * regress: the plugin not setting the attribute, and the plugin not being
 * registered in app.json at all.
 */

const { withAndroidManifest, AndroidConfig } = require('@expo/config-plugins');

/** The manifest attribute that permits cleartext HTTP for the whole app. */
const CLEARTEXT_ATTRIBUTE = 'android:usesCleartextTraffic';

/**
 * Set `android:usesCleartextTraffic="true"` on the main `<application>`.
 *
 * @param {import('@expo/config-types').ExpoConfig} config
 * @returns {import('@expo/config-types').ExpoConfig}
 */
const withLanCleartext = (config) =>
  withAndroidManifest(config, (cfg) => {
    // `getMainApplicationOrThrow` rather than an optional lookup: a manifest
    // with no <application> means prebuild's output shape changed, and silently
    // skipping is how this setting goes missing from a release build again.
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(
      cfg.modResults,
    );
    application.$[CLEARTEXT_ATTRIBUTE] = 'true';
    return cfg;
  });

module.exports = withLanCleartext;
module.exports.CLEARTEXT_ATTRIBUTE = CLEARTEXT_ATTRIBUTE;
