/**
 * SQL for resolving export handles to contact names — BACKLOG-3044 PR 4.
 *
 * Moved out of `electron/utils/exportUtils.ts` (2 sites). An export names each
 * conversation after the person it is with, so these two turn the raw handles on a
 * message — phone numbers and email addresses — into display names.
 *
 * ## The phone read matches on the LAST TEN DIGITS, in SQL, on both sides
 *
 * `substr(replace(replace(replace(<col>, '+', ''), '-', ''), ' ', ''), -10)` strips the
 * three characters that vary between how a number was typed and how it was stored, then
 * keeps the last ten digits. That is the same reduction the caller applies to the probe
 * values before binding them, so both sides of the comparison are normalised the same
 * way — a match rule is only correct if it is applied symmetrically.
 *
 * It runs over BOTH `phone_e164` and `phone_display`, because a contact may have been
 * saved with only one of them populated and an export that silently failed to name a
 * conversation is worse than a slow one. Note the consequence: the placeholder list is
 * spliced TWICE and the caller binds the same values twice, which is why the builder
 * takes one count and uses it in both positions.
 *
 * `ORDER BY c.display_name COLLATE NOCASE, c.id` is a total order, so an export
 * produces the same file for the same data rather than reshuffling between runs.
 *
 * Text is byte-identical to what it replaced. The placeholder lists are generated by
 * `placeholderList(n, sql`,`)` — comma with **no space**, matching the callers'
 * `.join(",")` exactly. The default separator is `, `, and using it here would have
 * changed every one of these statements by one character per placeholder.
 */

import { sql } from "./core/sqlText";
import type { SafeSql } from "./core/sqlText";
import { placeholderList } from "./core/sqlFragments";

/** Comma with no space — what `exportUtils`'s `.join(",")` produced. */
const COMMA = sql`,`;

/**
 * Contacts whose phone matches any of a set of numbers, by last-ten-digit suffix.
 *
 * Bound parameters: the normalised probe values **twice** — once for the `phone_e164`
 * arm and once for the `phone_display` arm, in that order. The caller passes
 * `[...normalizedPhones, ...normalizedPhones]`, and that duplication is required by the
 * statement rather than incidental.
 */
export function contactsByPhoneSuffixSql(phoneCount: number): SafeSql {
  const placeholders = placeholderList(phoneCount, COMMA);
  return sql`
      SELECT
        c.id AS contact_id,
        cp.phone_e164,
        cp.phone_display,
        c.display_name
      FROM contact_phones cp
      JOIN contacts c ON cp.contact_id = c.id
      WHERE substr(replace(replace(replace(cp.phone_e164, '+', ''), '-', ''), ' ', ''), -10) IN (${placeholders})
         OR substr(replace(replace(replace(cp.phone_display, '+', ''), '-', ''), ' ', ''), -10) IN (${placeholders})
      ORDER BY c.display_name COLLATE NOCASE, c.id
    `;
}

/**
 * Contacts holding any of a set of email addresses.
 *
 * `LOWER()` on both the stored column and — by the caller — the probe values, for the
 * same symmetry reason as the phone read. Bound parameters: the lower-cased addresses,
 * once.
 */
export function contactsByEmailSql(emailCount: number): SafeSql {
  const placeholders = placeholderList(emailCount, COMMA);
  return sql`
      SELECT
        c.id AS contact_id,
        LOWER(ce.email) as email,
        c.display_name
      FROM contact_emails ce
      JOIN contacts c ON ce.contact_id = c.id
      WHERE LOWER(ce.email) IN (${placeholders})
      ORDER BY c.display_name COLLATE NOCASE, c.id
    `;
}
