/**
 * Shared types for LLM AI Tools
 * SPRINT-005 Phase 1: AI Analysis Tools
 */

// ============================================================================
// Common Types
// ============================================================================

/**
 * Standard result wrapper for all LLM tool operations.
 * Provides consistent error handling and metrics across tools.
 */
export interface ToolResult<T> {
  success: boolean;
  data?: T;
  error?: string;
  tokensUsed?: { prompt: number; completion: number; total: number };
  latencyMs?: number;
}

// ============================================================================
// TASK-315: Message Analyzer Types
// ============================================================================

/**
 * Input for message analysis.
 */
export interface AnalyzeMessageInput {
  subject: string;
  body: string;
  sender: string;
  recipients: string[];
  date: string;
}

/**
 * Result of analyzing a single email message for real estate relevance.
 */
export interface MessageAnalysis {
  isRealEstateRelated: boolean;
  confidence: number; // 0-1
  transactionIndicators: {
    type: 'purchase' | 'sale' | 'lease' | null;
    stage: 'prospecting' | 'active' | 'pending' | 'closing' | 'closed' | null;
  };
  extractedEntities: {
    addresses: Array<{ value: string; confidence: number }>;
    amounts: Array<{ value: number; context: string }>;
    dates: Array<{ value: string; type: 'closing' | 'inspection' | 'other' }>;
    contacts: Array<{
      name: string;
      email?: string;
      phone?: string;
      suggestedRole?: string;
    }>;
  };
  reasoning: string;
  promptVersion?: string; // SHA of prompt used
}

// ============================================================================
// TASK-316: Contact Role Extractor Types
// ============================================================================

/**
 * Standard real estate transaction roles.
 */
export type ContactRole =
  | 'buyer'
  | 'seller'
  // BACKLOG-2859: ONE side-neutral agent role. `buyer_agent` / `seller_agent`
  // were removed here because this enum is a WRITE path — the extractor's
  // proposals become stored roles when a user accepts a suggested contact, so
  // leaving them would re-accumulate the values migration v68 collapsed.
  // (`buyer`/`seller` stay: the extractor may legitimately identify a principal
  // in an email even though neither is an assignable contact role.)
  | 'agent'
  | 'escrow'
  | 'title'
  | 'lender'
  | 'inspector'
  | 'appraiser'
  | 'attorney'
  | 'other';

/**
 * A single contact with their assigned role.
 */
export interface ContactRoleAssignment {
  contactId?: string; // Optional - caller may match later
  name: string;
  email?: string;
  phone?: string;
  role: ContactRole;
  confidence: number; // 0-1
  evidence: string[]; // Quotes from communications
}

/**
 * Result of extracting contact roles from communications.
 */
export interface ContactRoleExtraction {
  assignments: ContactRoleAssignment[];
  transactionContext?: {
    propertyAddress?: string;
    transactionType?: 'purchase' | 'sale' | 'lease';
  };
}

/**
 * Input for contact role extraction.
 */
export interface ExtractContactRolesInput {
  communications: Array<{
    subject: string;
    body: string;
    sender: string;
    recipients: string[];
    date: string;
  }>;
  knownContacts?: Array<{
    name: string;
    email?: string;
    phone?: string;
  }>;
  propertyAddress?: string;
}

// ============================================================================
// TASK-317: Transaction Clusterer Types
// ============================================================================

/**
 * A cluster of messages related to a single transaction.
 */
export interface TransactionCluster {
  clusterId: string; // UUID generated by tool
  propertyAddress: string;
  confidence: number; // 0-1
  transactionType: 'purchase' | 'sale' | 'lease' | null;
  stage: 'prospecting' | 'active' | 'pending' | 'closing' | 'closed' | null;
  communicationIds: string[]; // IDs of messages in this cluster
  dateRange: {
    start: string; // ISO date
    end: string; // ISO date
  };
  suggestedContacts: Array<{
    name: string;
    email?: string;
    role?: string;
  }>;
  summary: string; // Human-readable description
}

/**
 * Input for transaction clustering.
 */
export interface ClusterTransactionsInput {
  analyzedMessages: Array<{
    id: string; // Message ID for tracking
    subject: string;
    sender: string;
    recipients: string[];
    date: string;
    analysis: MessageAnalysis; // From TASK-315
  }>;
  existingTransactions?: Array<{
    id: string;
    propertyAddress: string;
    transactionType?: string;
  }>;
}

/**
 * Output from transaction clustering.
 */
export interface ClusterTransactionsOutput {
  clusters: TransactionCluster[];
  unclustered: string[]; // Message IDs that couldn't be clustered
}
